### ISSUE TITLE
Installation error (Ubuntu and Centos7)

### ISSUE THREAD

**Issue by piersoft** [datadotworld/ckanext-datadotworld#12]
hi, 

when i try to install, i receive many errors. 
Celery is needed but 3.x and not 4.x. 

At the end of installation:

paster --plugin=ckanext-datadotworld datadotworld init -c /etc/ckan/default/production.ini 

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/datadotworld/command.py", line 44, in command
    self._init()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/datadotworld/command.py", line 93, in _init
    main(argv, debug=False, repository=repository)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "<decorator-gen-9>", line 2, in version_control
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(*a, **kw)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/api.py", line 250, in version_control
    ControlledSchema.create(engine, repository, version)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/schema.py", line 139, in create
    repository = Repository(repository)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/repository.py", line 77, in __init__
    self.verify(path)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/migrate/versioning/repository.py", line 98, in verify
    raise exceptions.InvalidRepositoryError(path)
migrate.exceptions.InvalidRepositoryError: /usr/lib/ckan/default/lib/python2.7/site-packages/datadotworld_repository

Ckan 2.6.2 (same error on Ubuntu or Centos7 VM)

thanks

**Comment by iaroslav13** [comment]
Hi @piersoft,

Thanks for submitting the issue. 

It looks like this can sometimes happen when the extension is installed using pip install. We will fix the issue shortly.

For you can uninstall the extension suing `pip uninstall ckanext-datadotworld ` and then use the [Development Installation](https://github.com/datadotworld/ckanext-datadotworld#development-installation).

I will let you know when the fix is ready and merged.

As for the Celery 4.x, unfortunately CKAN doesn't support this version, therefore all the extensions require Celery 3.x. If you follow the [Development Installation](https://github.com/datadotworld/ckanext-datadotworld#development-installation) instructions, the correct version will be installed.

Cheers

**Comment by piersoft** [comment]
ok. now it's working on centos7.

thanks

2017-06-08 11:43 GMT+02:00 Iaroslav Pereiaslovets <notifications@github.com>
:

**Comment by iaroslav13** [comment]
@piersoft This should now work with `pip install`
