### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'cs'

### ISSUE THREAD

**Issue by actongorton** [datadotworld/ckanext-datadotworld#31]
```
$ paster --plugin=ckan celeryd run -c production.ini 
WARNING: This function is deprecated. Use `paster jobs worker` instead.
No handlers could be found for logger "ckan.lib.celery_app"
[2017-10-16 17:21:47,113: WARNING/MainProcess] /usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2017-10-16 17:21:47,123: ERROR/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: 'cs'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    self.on_start()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/apps/worker.py", line 169, in on_start
    string(self.colored.cyan(' \n', self.startup_info())),
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/apps/worker.py", line 230, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/backends/base.py", line 118, in as_uri
    url = maybe_sanitize_url(self.url or '')
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/kombu/utils/url.py", line 58, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'cs'
```

**Comment by iaroslav13** [comment]
Hi @acer9997,

Thank you for submitting the issue. It looks like you are using CKAN 2.7 which has a different Job Queue - [RQ](http://python-rq.org/). This is described in the README file:

> All versions support celery backend, but version 2.7 will use RQ. There are no changes required to use new backend - just start it using:
> paster --plugin=ckan jobs worker -c /config.ini
> instead of:
> paster --plugin=ckan celeryd run -c /config.ini
> Details at http://docs.ckan.org/en/latest/maintaining/background-tasks.html

I am sorry if the documentation doesn't highlight it enough. Do you have any suggestions on how we can improve the documentation to avoid similar confusion in future?

Regards,
Iaroslav

**Comment by acer9997** [comment]
Hi @iaroslav13,

I see what happened!

In my mind, I think what happened was seeing the redis dependency listed with the ckan installation instructions and then blanking on the ckan version number when I was reading the data.world instructions. This probably wouldn't have been lost on most people paying better attention. Maybe a dummy alert under step 5 in the readme for people like me? :)

Thanks so much!
